# Generated by Django 5.2.8 on 2025-11-14 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultades',
            fields=[
                ('id_facultad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Facultades',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=255)),
                ('contrasena', models.CharField(max_length=255)),
                ('es_admin', models.IntegerField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Tienditas',
            fields=[
                ('id_tiendita', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('foro_url', models.CharField(blank=True, max_length=255, null=True)),
                ('id_facultad', models.ForeignKey(blank=True, db_column='id_facultad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cafeteria.facultades')),
            ],
            options={
                'db_table': 'Tienditas',
            },
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id_menu', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_tiendita', models.ForeignKey(blank=True, db_column='id_tiendita', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cafeteria.tienditas')),
            ],
            options={
                'db_table': 'Menus',
            },
        ),
    ]
