# Generated by Django 5.2.8 on 2025-11-19 22:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultades',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='menus',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tienditas',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='default@email.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Resenas',
            fields=[
                ('id_resena', models.AutoField(primary_key=True, serialize=False)),
                ('calificacion', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='fecha_res')),
                ('id_tiendita', models.ForeignKey(db_column='id_tiendita', on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='cafeteria.tienditas')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cafeteria.usuarios')),
            ],
            options={
                'db_table': 'resenas',
                'ordering': ['-fecha_registro'],
                'managed': True,
            },
        ),
    ]
