# Generated by Django 5.2.8 on 2025-11-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_alter_facultades_options_alter_menus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienditas',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tienditas',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=15, max_digits=20, null=True),
        ),
    ]
