# Generated by Django 5.2.8 on 2025-11-07 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0002_alter_usuarios_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False},
        ),
    ]
