# Generated by Django 5.2.8 on 2025-11-21 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0003_tienditas_latitud_tienditas_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienditas',
            name='imagen_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
