# Generated by Django 5.2.8 on 2025-11-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0004_tienditas_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='tienditas',
            name='hora_apertura',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tienditas',
            name='hora_cierre',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
