# Generated by Django 5.2.8 on 2025-11-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeteria', '0005_tienditas_hora_apertura_tienditas_hora_cierre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menus',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
